spring.application.name=product-service

server.port=8081


# ==========================================
# EUREKA
# ==========================================

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


# ==========================================
# ACTUATOR
# ==========================================

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always


# ==========================================
# INVENTORY CIRCUIT BREAKER
# ==========================================

resilience4j.circuitbreaker.instances.inventoryService.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.inventoryService.sliding-window-size=5
resilience4j.circuitbreaker.instances.inventoryService.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.inventoryService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.inventoryService.wait-duration-in-open-state=60s
resilience4j.circuitbreaker.instances.inventoryService.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.instances.inventoryService.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.inventoryService.register-health-indicator=true


# ==========================================
# RECOMMENDATION CIRCUIT BREAKER
# ==========================================

resilience4j.circuitbreaker.instances.recommendationService.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.recommendationService.sliding-window-size=5
resilience4j.circuitbreaker.instances.recommendationService.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.recommendationService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.recommendationService.wait-duration-in-open-state=60s
resilience4j.circuitbreaker.instances.recommendationService.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.instances.recommendationService.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.recommendationService.register-health-indicator=true


# ==========================================
# DISTRIBUTED TRACING - ZIPKIN
# ==========================================

management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.tracing.export.zipkin.endpoint=http://localhost:9411/api/v2/spans