spring.application.name=api-gateway

server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# =========================
# PRODUCT SERVICE ROUTE
# =========================

spring.cloud.gateway.server.webmvc.routes[0].id=product-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://product-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/products/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=CircuitBreaker=productGatewayCircuitBreaker

# =========================
# INVENTORY SERVICE ROUTE
# =========================

spring.cloud.gateway.server.webmvc.routes[1].id=inventory-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://inventory-service
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/inventory/**

# =========================
# RECOMMENDATION SERVICE ROUTE
# =========================

spring.cloud.gateway.server.webmvc.routes[2].id=recommendation-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://recommendation-service
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/recommendations/**

# =========================
# GATEWAY CIRCUIT BREAKER
# =========================

resilience4j.circuitbreaker.instances.productGatewayCircuitBreaker.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.productGatewayCircuitBreaker.sliding-window-size=5
resilience4j.circuitbreaker.instances.productGatewayCircuitBreaker.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.productGatewayCircuitBreaker.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.productGatewayCircuitBreaker.wait-duration-in-open-state=30s
resilience4j.circuitbreaker.instances.productGatewayCircuitBreaker.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.instances.productGatewayCircuitBreaker.automatic-transition-from-open-to-half-open-enabled=true
# Resilience4j Bulkhead
resilience4j.bulkhead.instances.productBulkhead.maxConcurrentCalls=3
resilience4j.bulkhead.instances.productBulkhead.maxWaitDuration=0
# Resilience4j TimeLimiter
resilience4j.timelimiter.instances.productTimeLimiter.timeoutDuration=3s
resilience4j.timelimiter.instances.productTimeLimiter.cancelRunningFuture=true